### ISSUE TITLE
Symfony 5 upgrade

### ISSUE THREAD

**Issue by mevdschee** [Amsterdam/makkelijkemarkt-api#35]
Hi @maartendekeizer,

I'm working on a Symfony 5.1 upgrade, see:

https://github.com/mevdschee/makkelijkemarkt-api/tree/symfony5

Kind regards, Maurits

**Comment by timfi-amsterdam** [comment]
stalled

**Comment by mevdschee** [comment]
The symfony 5 port was already executed by @maartendekeizer on a different branch, but never pushed to this repo even though it had been billed and payed for by the city of Amsterdam. I wouldn't call that "stalled" ;-)

**Comment by maartendekeizer** [comment]
@mevdschee Please do you homework, the Symfony 5 upgrade is published in january 2021 in *this* repo
https://github.com/Amsterdam/makkelijkemarkt-api/commit/938961157fcd3bc21adbc769f193e70725c0d2f8

**Comment by mevdschee** [comment]
Okay .. updated..
